using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*/

namespace Problem12
{
    class Program
    {
        static void Main(string[] args)
        {
            Stopwatch sw = new Stopwatch();
            sw.Start();
            Console.WriteLine(NumberDelete());
            sw.Stop();
            Console.WriteLine("\n" + sw.Elapsed);
            Console.ReadLine();
        }
        static ulong NumberDelete()
        {
            ulong result = 0;
            int count = 0;
            ulong number = 0;
            int prom = 0;
            ulong input = 1;
            for (result=2; ; result++)
            {
                count = 0;
                input += result;
                if (input % 2 != 0) continue;
                number++;
                
                for (ulong s = 1; s < input; s++)
                {
                    number++;
                    if (input % s == 0) count++;
                    if (s > (input / 10)) break;
                }
                if (count > prom) Console.WriteLine(input + " " + count);
                prom = (prom > count) ? prom : count;
                if (count > 490) break;
            }
            Console.WriteLine(result + " "+ input+" " + count + " " + number);
            return result;
        }
    }
}
